[package]
name = "libalpha"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libalpha"
crate-type = ["cdylib"]

[dependencies]


[dependencies.pyo3]
version = "0.14.1"
features = ["extension-module"]
